server:
  port: 8080   # par défaut, chaque profil peut le surcharger

spring:
  application:
    name: accord-Service
  profiles:
    active: prod  # profil par défaut
  mail:
    host: mailer.gov.bf
    port: 587
    username: alertesmae@gmail.com
    password: 'fevh duqq bksu zlcw'
    protocol: smtp
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: ${spring.mail.host}
    test-connection: false

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

# Configuration personnalisée commune
app:
  storage:
    path: ./datas
  security:
    attempts:
      timeout: 5   # minutes
      max: 5       # tentatives max
