server:
  port: 8082

spring:
  profiles:
    active: prod

  application:
    name: DgpeService

  # Configuration du service mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: alertesmae@gmail.com
    password: 'fevh duqq bksu zlcw'
    protocol: smtp
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.ssl.trust: smtp.gmail.com
    test-connection: false

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB

# Configuration personnalisée
app:
  storage:
    path: ./datas

  security:
    attempts:
      timeout: 5  # En nombre de minutes
      max: 5      # Nombre de tentatives autorisées
