package com.bakouan.app.enums;

public enum EDocument {
    NOTE_VERBALE,
    CNIB,
    PASSEPORT_ORDINAIRE,
    PASSEPORT_DIPLOMATIQUE,
    PASSEPORT_SERVICE,
    CERTIFICAT_PRISE_SERVICE,
    ACTE_MARIAGE,
    PHOTO,
    DECRET_NOMINATION,
    CERTIFICAT_CHIFFRE_AFFAIRE,
    SITUATION_FISCALE,
    LISTE_DELEGATION,
    AUTRE
}
