package com.bakouan.app.enums;

public enum ETypeCarte {
    CARTE_PERSONNEL_AMBASSADE,
    CARTE_PERSONNEL_ORGANISME_INTERNATIONAUX,
    CARTE_PERSONNEL_ADMINISTRATIF_TECHNIQUE,
    CARTE_AMBASSABEUR
}