package com.bakouan.app.enums;

public enum ETypeCarteAcces {
    CARTE_ACCES_SALON_PARTICULIER,
    CARTE_ACCES_SALON_DIPLOMATIQUE,
    CARTE_ACCES_SALON_ADMINISTRATION,
    CARTE_ACCES_SALON_ANCIEN_MINISTRE_PRESIDENT
}
